version = 3.11.5
runner.dialect = scala3
maxColumn = 100
includeCurlyBraceInSelectChains = false
newlines {
  alwaysBeforeMultilineDef = false
}
importSelectors = singleLine
continuationIndent {
  defnSite = 2
  extendSite = 2
}
rewrite {
  scala3 {
    convertToNewSyntax = true
    removeOptionalBraces = {
      enabled = true
      fewerBracesMinSpan = 2
      fewerBracesMaxSpan = 1024
      oldSyntaxToo = true
    }
  }
  rules = [RedundantBraces]
  redundantBraces {
    stringInterpolation = true
    generalExpressions = true
  }
}
